-- Script SQL để cập nhật tên 150 bài tập sang tiếng Việt
-- Chạy script này trong SQL Server hoặc thông qua Entity Framework

UPDATE ExerciseTemplates SET Name = 'HIIT 20 phút' WHERE Id = 1;
UPDATE ExerciseTemplates SET Name = 'Toàn thân 30 phút' WHERE Id = 2;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ linh hoạt' WHERE Id = 3;
UPDATE ExerciseTemplates SET Name = 'Cardio nhanh 10 phút' WHERE Id = 4;
UPDATE ExerciseTemplates SET Name = 'Tập tay vai' WHERE Id = 5;
UPDATE ExerciseTemplates SET Name = 'Tập chân mông' WHERE Id = 6;
UPDATE ExerciseTemplates SET Name = 'Tập bụng cơ bản' WHERE Id = 7;
UPDATE ExerciseTemplates SET Name = 'Yoga 30 phút' WHERE Id = 8;
UPDATE ExerciseTemplates SET Name = 'Đi bộ nhanh 30 phút' WHERE Id = 9;
UPDATE ExerciseTemplates SET Name = 'Chạy bộ 25 phút' WHERE Id = 10;
UPDATE ExerciseTemplates SET Name = 'Tạ Kettlebell' WHERE Id = 11;
UPDATE ExerciseTemplates SET Name = 'Pilates bụng 20 phút' WHERE Id = 12;
UPDATE ExerciseTemplates SET Name = 'Tabata 16 phút' WHERE Id = 13;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ phục hồi' WHERE Id = 14;
UPDATE ExerciseTemplates SET Name = 'Tập tay không 20 phút' WHERE Id = 15;
UPDATE ExerciseTemplates SET Name = 'Đạp xe 45 phút' WHERE Id = 16;
UPDATE ExerciseTemplates SET Name = 'Đi bộ leo dốc 40 phút' WHERE Id = 17;
UPDATE ExerciseTemplates SET Name = 'Dây kháng lực toàn thân' WHERE Id = 18;
UPDATE ExerciseTemplates SET Name = 'Tập tạ nặng' WHERE Id = 19;
UPDATE ExerciseTemplates SET Name = 'Cardio nhẹ 30 phút' WHERE Id = 20;
UPDATE ExerciseTemplates SET Name = 'Chạy nước rút 20 phút' WHERE Id = 21;
UPDATE ExerciseTemplates SET Name = 'Tạ đơn 30 phút' WHERE Id = 22;
UPDATE ExerciseTemplates SET Name = 'Phục hồi nhẹ 20 phút' WHERE Id = 23;
UPDATE ExerciseTemplates SET Name = 'EMOM 25 phút' WHERE Id = 24;
UPDATE ExerciseTemplates SET Name = 'Chèo thuyền 30 phút' WHERE Id = 25;
UPDATE ExerciseTemplates SET Name = 'Cân bằng ổn định' WHERE Id = 26;
UPDATE ExerciseTemplates SET Name = 'Nhảy chân 25 phút' WHERE Id = 27;
UPDATE ExerciseTemplates SET Name = 'Chạy địa hình 40 phút' WHERE Id = 28;
UPDATE ExerciseTemplates SET Name = 'Yoga ghế 20 phút' WHERE Id = 29;
UPDATE ExerciseTemplates SET Name = 'Tốc độ bền bỉ 35 phút' WHERE Id = 30;
UPDATE ExerciseTemplates SET Name = 'Sức mạnh chức năng 30 phút' WHERE Id = 31;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ nhẹ nhàng 10 phút' WHERE Id = 32;
UPDATE ExerciseTemplates SET Name = 'Boxing Cardio 25 phút' WHERE Id = 33;
UPDATE ExerciseTemplates SET Name = 'Tạ đòn 60 phút' WHERE Id = 34;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ buổi sáng 15 phút' WHERE Id = 35;
UPDATE ExerciseTemplates SET Name = 'Chạy lên dốc 20 phút' WHERE Id = 36;
UPDATE ExerciseTemplates SET Name = 'TRX toàn thân' WHERE Id = 37;
UPDATE ExerciseTemplates SET Name = 'Massage cơ & Giãn' WHERE Id = 38;
UPDATE ExerciseTemplates SET Name = 'Chạy bền 60 phút' WHERE Id = 39;
UPDATE ExerciseTemplates SET Name = 'Tập bụng 15 phút' WHERE Id = 40;
UPDATE ExerciseTemplates SET Name = 'Thể dục dưới nước 30 phút' WHERE Id = 41;
UPDATE ExerciseTemplates SET Name = 'Thang tốc độ 20 phút' WHERE Id = 42;
UPDATE ExerciseTemplates SET Name = 'Đi bộ có tạ 30 phút' WHERE Id = 43;
UPDATE ExerciseTemplates SET Name = 'Tập mông 25 phút' WHERE Id = 44;
UPDATE ExerciseTemplates SET Name = 'Khởi động động 10 phút' WHERE Id = 45;
UPDATE ExerciseTemplates SET Name = 'Chạy nước rút 30 phút' WHERE Id = 46;
UPDATE ExerciseTemplates SET Name = 'Tăng cơ tay 45 phút' WHERE Id = 47;
UPDATE ExerciseTemplates SET Name = 'Cân bằng 20 phút' WHERE Id = 48;
UPDATE ExerciseTemplates SET Name = 'Chạy Tempo 35 phút' WHERE Id = 49;
UPDATE ExerciseTemplates SET Name = 'Vận động chức năng 30 phút' WHERE Id = 50;
UPDATE ExerciseTemplates SET Name = 'Đi bộ phục hồi 20 phút' WHERE Id = 51;
UPDATE ExerciseTemplates SET Name = 'CrossFit WOD 20 phút' WHERE Id = 52;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ & Thở 15 phút' WHERE Id = 53;
UPDATE ExerciseTemplates SET Name = 'Máy chạy dốc 30 phút' WHERE Id = 54;
UPDATE ExerciseTemplates SET Name = 'Sức bền 40 phút' WHERE Id = 55;
UPDATE ExerciseTemplates SET Name = 'Calisthenics 25 phút' WHERE Id = 56;
UPDATE ExerciseTemplates SET Name = 'Sức mạnh bùng nổ 30 phút' WHERE Id = 57;
UPDATE ExerciseTemplates SET Name = 'Pilates nhẹ 30 phút' WHERE Id = 58;
UPDATE ExerciseTemplates SET Name = 'Đạp xe nhanh 20 phút' WHERE Id = 59;
UPDATE ExerciseTemplates SET Name = 'Tập chân 50 phút' WHERE Id = 60;
UPDATE ExerciseTemplates SET Name = 'Ổn định bụng 30 phút' WHERE Id = 61;
UPDATE ExerciseTemplates SET Name = 'Yoga buổi sáng 20 phút' WHERE Id = 62;
UPDATE ExerciseTemplates SET Name = 'Chèo thuyền 15 phút' WHERE Id = 63;
UPDATE ExerciseTemplates SET Name = 'Tập sức mạnh A' WHERE Id = 64;
UPDATE ExerciseTemplates SET Name = 'Giãn sâu 30 phút' WHERE Id = 65;
UPDATE ExerciseTemplates SET Name = 'Chạy Fartlek 30 phút' WHERE Id = 66;
UPDATE ExerciseTemplates SET Name = 'Tập tay 40 phút' WHERE Id = 67;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ linh hoạt 20 phút' WHERE Id = 68;
UPDATE ExerciseTemplates SET Name = 'Chạy nước rút & Chạy bộ 30 phút' WHERE Id = 69;
UPDATE ExerciseTemplates SET Name = 'Kettlebell 30 phút' WHERE Id = 70;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ nhẹ 10 phút' WHERE Id = 71;
UPDATE ExerciseTemplates SET Name = 'Đạp xe Tempo 45 phút' WHERE Id = 72;
UPDATE ExerciseTemplates SET Name = 'Tăng cơ toàn thân' WHERE Id = 73;
UPDATE ExerciseTemplates SET Name = 'Thở & Giãn 15 phút' WHERE Id = 74;
UPDATE ExerciseTemplates SET Name = 'Chạy bộ 45 phút' WHERE Id = 75;
UPDATE ExerciseTemplates SET Name = 'Sức mạnh 25 phút' WHERE Id = 76;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ 45 phút' WHERE Id = 77;
UPDATE ExerciseTemplates SET Name = 'Leo dốc 30 phút' WHERE Id = 78;
UPDATE ExerciseTemplates SET Name = 'Sức mạnh bùng nổ 20 phút' WHERE Id = 79;
UPDATE ExerciseTemplates SET Name = 'Đi bộ nhẹ 15 phút' WHERE Id = 80;
UPDATE ExerciseTemplates SET Name = 'Đốt mỡ bụng 15 phút' WHERE Id = 81;
UPDATE ExerciseTemplates SET Name = 'Yoga phục hồi 45 phút' WHERE Id = 82;
UPDATE ExerciseTemplates SET Name = 'Chạy kim tự tháp 30 phút' WHERE Id = 83;
UPDATE ExerciseTemplates SET Name = 'Tạ đơn phức hợp 20 phút' WHERE Id = 84;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ 10 phút' WHERE Id = 85;
UPDATE ExerciseTemplates SET Name = 'Đạp xe bền 60 phút' WHERE Id = 86;
UPDATE ExerciseTemplates SET Name = 'Xây dựng sức mạnh 50 phút' WHERE Id = 87;
UPDATE ExerciseTemplates SET Name = 'Pilates 30 phút' WHERE Id = 88;
UPDATE ExerciseTemplates SET Name = 'Chạy tốc độ 20 phút' WHERE Id = 89;
UPDATE ExerciseTemplates SET Name = 'Tập chân 35 phút' WHERE Id = 90;
UPDATE ExerciseTemplates SET Name = 'Giãn nhẹ 20 phút' WHERE Id = 91;
UPDATE ExerciseTemplates SET Name = 'Đạp xe 30 phút' WHERE Id = 92;
UPDATE ExerciseTemplates SET Name = 'Toàn thân 40 phút' WHERE Id = 93;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ 25 phút' WHERE Id = 94;
UPDATE ExerciseTemplates SET Name = 'Chạy nước rút 25 phút' WHERE Id = 95;
UPDATE ExerciseTemplates SET Name = 'Tăng cơ 30 phút' WHERE Id = 96;
UPDATE ExerciseTemplates SET Name = 'Giãn nhẹ 30 phút' WHERE Id = 97;
UPDATE ExerciseTemplates SET Name = 'Chạy Tempo 20 phút' WHERE Id = 98;
UPDATE ExerciseTemplates SET Name = 'Kettlebell 45 phút' WHERE Id = 99;
UPDATE ExerciseTemplates SET Name = 'Giãn & Thở 15 phút' WHERE Id = 100;
UPDATE ExerciseTemplates SET Name = 'Cardio tổng hợp 30 phút' WHERE Id = 101;
UPDATE ExerciseTemplates SET Name = 'Tập tay 30 phút' WHERE Id = 102;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ 10 phút' WHERE Id = 103;
UPDATE ExerciseTemplates SET Name = 'Chạy nước rút 30 phút' WHERE Id = 104;
UPDATE ExerciseTemplates SET Name = 'Sức mạnh 45 phút' WHERE Id = 105;
UPDATE ExerciseTemplates SET Name = 'Yoga nhẹ 30 phút' WHERE Id = 106;
UPDATE ExerciseTemplates SET Name = 'Chạy bộ 20 phút' WHERE Id = 107;
UPDATE ExerciseTemplates SET Name = 'Tập chân 30 phút' WHERE Id = 108;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ 20 phút' WHERE Id = 109;
UPDATE ExerciseTemplates SET Name = 'Leo dốc 30 phút' WHERE Id = 110;
UPDATE ExerciseTemplates SET Name = 'Sức mạnh 60 phút' WHERE Id = 111;
UPDATE ExerciseTemplates SET Name = 'Pilates bụng 30 phút' WHERE Id = 112;
UPDATE ExerciseTemplates SET Name = 'Chạy nước rút 15 phút' WHERE Id = 113;
UPDATE ExerciseTemplates SET Name = 'Tạ đơn 45 phút' WHERE Id = 114;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ 10 phút' WHERE Id = 115;
UPDATE ExerciseTemplates SET Name = 'Chạy bền 30 phút' WHERE Id = 116;
UPDATE ExerciseTemplates SET Name = 'Xây dựng sức mạnh 30 phút' WHERE Id = 117;
UPDATE ExerciseTemplates SET Name = 'Giãn nhẹ 30 phút' WHERE Id = 118;
UPDATE ExerciseTemplates SET Name = 'Tabata 12 phút' WHERE Id = 119;
UPDATE ExerciseTemplates SET Name = 'Toàn thân 30 phút' WHERE Id = 120;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ 60 phút' WHERE Id = 121;
UPDATE ExerciseTemplates SET Name = 'Chạy nước rút 45 phút' WHERE Id = 122;
UPDATE ExerciseTemplates SET Name = 'Tăng cơ 45 phút' WHERE Id = 123;
UPDATE ExerciseTemplates SET Name = 'Giãn nhẹ 45 phút' WHERE Id = 124;
UPDATE ExerciseTemplates SET Name = 'Đạp xe 45 phút' WHERE Id = 125;
UPDATE ExerciseTemplates SET Name = 'Tập chân 45 phút' WHERE Id = 126;
UPDATE ExerciseTemplates SET Name = 'Pilates phục hồi 20 phút' WHERE Id = 127;
UPDATE ExerciseTemplates SET Name = 'Chạy tốc độ 30 phút' WHERE Id = 128;
UPDATE ExerciseTemplates SET Name = 'Sức mạnh 60 phút' WHERE Id = 129;
UPDATE ExerciseTemplates SET Name = 'Giãn & Thở 30 phút' WHERE Id = 130;
UPDATE ExerciseTemplates SET Name = 'Chạy lên dốc 30 phút' WHERE Id = 131;
UPDATE ExerciseTemplates SET Name = 'Tập tay 50 phút' WHERE Id = 132;
UPDATE ExerciseTemplates SET Name = 'Yoga nhẹ 45 phút' WHERE Id = 133;
UPDATE ExerciseTemplates SET Name = 'Chạy bộ 60 phút' WHERE Id = 134;
UPDATE ExerciseTemplates SET Name = 'Xây dựng sức mạnh 60 phút' WHERE Id = 135;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ 90 phút' WHERE Id = 136;
UPDATE ExerciseTemplates SET Name = 'Chạy kim tự tháp 45 phút' WHERE Id = 137;
UPDATE ExerciseTemplates SET Name = 'Kettlebell phức hợp 30 phút' WHERE Id = 138;
UPDATE ExerciseTemplates SET Name = 'Pilates bụng 45 phút' WHERE Id = 139;
UPDATE ExerciseTemplates SET Name = 'Chạy Tempo 45 phút' WHERE Id = 140;
UPDATE ExerciseTemplates SET Name = 'Toàn thân 60 phút' WHERE Id = 141;
UPDATE ExerciseTemplates SET Name = 'Giãn nhẹ 45 phút' WHERE Id = 142;
UPDATE ExerciseTemplates SET Name = 'Đạp xe 60 phút' WHERE Id = 143;
UPDATE ExerciseTemplates SET Name = 'Tăng cơ 60 phút' WHERE Id = 144;
UPDATE ExerciseTemplates SET Name = 'Giãn cơ 120 phút' WHERE Id = 145;
UPDATE ExerciseTemplates SET Name = 'Chạy nước rút 60 phút' WHERE Id = 146;
UPDATE ExerciseTemplates SET Name = 'Sức mạnh 90 phút' WHERE Id = 147;
UPDATE ExerciseTemplates SET Name = 'Pilates phục hồi 45 phút' WHERE Id = 148;
UPDATE ExerciseTemplates SET Name = 'Chạy bền 90 phút' WHERE Id = 149;
UPDATE ExerciseTemplates SET Name = 'Toàn thân tối ưu 75 phút' WHERE Id = 150;
